train:
  _target_: src.datasets.LJSpeechDataset
  audio_dir: /home/timsenin/pytorch_project_template/data/LJSpeech-1.1/wavs
  max_audio_length: 20
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LJSpeechDataset
  audio_dir: /home/timsenin/pytorch_project_template/data/LJSpeech-1.1/wavs
  max_audio_length: 20
  instance_transforms: ${transforms.instance_transforms.inference}
