_target_: src.model.hi_fi_gan.HiFiGAN
generator_config: {
  "input_channels": 80,
  "hidden_channels": 512,
  "upsample_kernels": [16, 16, 4, 4],
  "mrf_kernels": [3, 7, 11],
  "mrf_dilations": [
    [[1, 1], [3, 1], [5, 1]],
    [[1, 1], [3, 1], [5, 1]],
    [[1, 1], [3, 1], [5, 1]]
  ]
}
mpd_config: {
  "periods": [2, 3, 5, 7, 11],
  "kernel_size": 5,
  "stride": 3,
  "channels": [32, 128, 512, 1024]
}
msd_config: {
  "scales": [1, 2, 4],
  "kernel_sizes": [15, 41, 41, 41, 41, 41, 5],
  "strides": [1, 2, 2, 4, 4, 1, 1],
  "groups": [1, 4, 16, 16, 16, 16, 1],
  "channels": [128, 128, 256, 512, 1024, 1024, 1024]
}
