defaults:
  - model: hi_fi_gan
  - writer: wandb
  - metrics: mos
  - datasets: lj_speech
  - dataloader: a100
  - transforms: example_only_instance
  - _self_
optimizer_discriminator:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas:
    - 0.8
    - 0.999
optimizer_generator:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas:
    - 0.8
    - 0.999
lr_scheduler_discriminator:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
lr_scheduler_generator:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
loss_function:
  _target_: src.loss.HiFiGANLoss
trainer:
  log_step: 25
  n_epochs: 100
  epoch_len: 102
  device_tensors: ["audio", "spectrogram"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: cuda # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max MOS" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
