train:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.wav_augs.spectrogram.MelSpectrogram

inference:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.wav_augs.spectrogram.MelSpectrogram
